// <auto-generated />
using System;
using ECommerceNew.Infrastructure.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerceNew.Infrastructure.Migrations
{
    [DbContext(typeof(ECommerceDbContext))]
    [Migration("20260228180238_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerceNew.Domain.Entities.ProductSide.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CartItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.ProductSide.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.ProductSide.ProductCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Buy on Installments"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Large Domestic Appliances"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Mobile Phones"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Sales"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Laptops"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Game Consoles"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Art and Collection"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Desktop Computers"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Services"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Training Inventory"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Bicycles"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Hiking and Tourism"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Computer Hardware"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Bed"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Watches & Accessories"
                        },
                        new
                        {
                            CategoryId = 16,
                            CategoryName = "Outlet"
                        },
                        new
                        {
                            CategoryId = 17,
                            CategoryName = "Pets"
                        },
                        new
                        {
                            CategoryId = 18,
                            CategoryName = "Kids"
                        },
                        new
                        {
                            CategoryId = 19,
                            CategoryName = "TV"
                        },
                        new
                        {
                            CategoryId = 20,
                            CategoryName = "Small Household Appliances"
                        },
                        new
                        {
                            CategoryId = 21,
                            CategoryName = "Books"
                        },
                        new
                        {
                            CategoryId = 22,
                            CategoryName = "Kitchen"
                        },
                        new
                        {
                            CategoryId = 23,
                            CategoryName = "Loud Speakers"
                        },
                        new
                        {
                            CategoryId = 24,
                            CategoryName = "Headphones"
                        },
                        new
                        {
                            CategoryId = 25,
                            CategoryName = "Hunting Equipment"
                        },
                        new
                        {
                            CategoryId = 26,
                            CategoryName = "Monitors"
                        },
                        new
                        {
                            CategoryId = 27,
                            CategoryName = "Shoes"
                        },
                        new
                        {
                            CategoryId = 28,
                            CategoryName = "Industrial Equipment"
                        },
                        new
                        {
                            CategoryId = 29,
                            CategoryName = "Music"
                        },
                        new
                        {
                            CategoryId = 30,
                            CategoryName = "Super VIP"
                        });
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.ProductSide.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.UserSide.EmailVerification", b =>
                {
                    b.Property<int>("VerificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VerificationId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VerificationId");

                    b.ToTable("EmailVerifications");
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.UserSide.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Client"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Admin"
                        });
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.UserSide.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@system.local",
                            FirstName = "System",
                            IsActive = true,
                            LastName = "Administrator",
                            PasswordHash = "AQAAAAEAACcQAAAAEIM9Gb9aogKUXsuO5FOBcvftv4BETrT9VGpGfYB7ER2nxW8eV2+oCBpkAZt8oxnXNw==",
                            PhoneNumber = "",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.ProductSide.CartItem", b =>
                {
                    b.HasOne("ECommerceNew.Domain.Entities.ProductSide.Product", "product")
                        .WithMany("cartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ECommerceNew.Domain.Entities.UserSide.User", "user")
                        .WithMany("cartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.ProductSide.Product", b =>
                {
                    b.HasOne("ECommerceNew.Domain.Entities.ProductSide.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ECommerceNew.Domain.Entities.UserSide.User", "user")
                        .WithMany("products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductCategory");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.ProductSide.ProductImage", b =>
                {
                    b.HasOne("ECommerceNew.Domain.Entities.ProductSide.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.UserSide.User", b =>
                {
                    b.HasOne("ECommerceNew.Domain.Entities.UserSide.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.ProductSide.Product", b =>
                {
                    b.Navigation("ProductImages");

                    b.Navigation("cartItems");
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.ProductSide.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.UserSide.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.UserSide.User", b =>
                {
                    b.Navigation("cartItems");

                    b.Navigation("products");
                });
#pragma warning restore 612, 618
        }
    }
}
