// <auto-generated />
using System;
using ECommerceNew.Infrastructure.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerceNew.Infrastructure.Migrations
{
    [DbContext(typeof(ECommerceDbContext))]
    [Migration("20260314142816_AddedParentCategories")]
    partial class AddedParentCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerceNew.Domain.Entities.ProductSide.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CartId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.ProductSide.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.ProductSide.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.ProductSide.ProductCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Laptops"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Desktop Computers"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Computer Components"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Peripherals"
                        },
                        new
                        {
                            CategoryId = 20,
                            CategoryName = "Networking Equipment"
                        },
                        new
                        {
                            CategoryId = 29,
                            CategoryName = "Smartphones & Tablets"
                        },
                        new
                        {
                            CategoryId = 30,
                            CategoryName = "Repair & Services"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Processors (CPU)",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Graphics Cards (GPU)",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Motherboards",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Memory (RAM)",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Storage (SSD / HDD / NVMe)",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Power Supplies (PSU)",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "PC Cases",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Cooling Systems",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Monitors",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Keyboards",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Mice",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            CategoryId = 16,
                            CategoryName = "Headsets",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            CategoryId = 17,
                            CategoryName = "Speakers",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            CategoryId = 18,
                            CategoryName = "Webcams & Microphones",
                            ParentCategoryId = 12
                        },
                        new
                        {
                            CategoryId = 21,
                            CategoryName = "Routers & Modems",
                            ParentCategoryId = 20
                        },
                        new
                        {
                            CategoryId = 22,
                            CategoryName = "Network Switches",
                            ParentCategoryId = 20
                        },
                        new
                        {
                            CategoryId = 23,
                            CategoryName = "Phone Accessories",
                            ParentCategoryId = 29
                        },
                        new
                        {
                            CategoryId = 24,
                            CategoryName = "Chargers & Power Banks",
                            ParentCategoryId = 29
                        },
                        new
                        {
                            CategoryId = 25,
                            CategoryName = "PC Assembly",
                            ParentCategoryId = 30
                        },
                        new
                        {
                            CategoryId = 26,
                            CategoryName = "PC Repair",
                            ParentCategoryId = 30
                        },
                        new
                        {
                            CategoryId = 27,
                            CategoryName = "Laptop Repair",
                            ParentCategoryId = 30
                        },
                        new
                        {
                            CategoryId = 28,
                            CategoryName = "Data Recovery",
                            ParentCategoryId = 30
                        });
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.ProductSide.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.ProductSide.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.StoreInfo.StoreInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkingHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StoreInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Tech Street, Tbilisi, Georgia",
                            Email = "temomeshveliani777@gmail.com",
                            LogoUrl = "/images/logo.png",
                            Name = "EkkoShop",
                            Phone = "+995 599 931 611",
                            WorkingHours = "Mon-Fri 9:00-18:00"
                        });
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.UserSide.EmailVerification", b =>
                {
                    b.Property<int>("VerificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VerificationId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VerificationId");

                    b.ToTable("EmailVerifications");
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.UserSide.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Client"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Admin"
                        });
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.UserSide.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@system.local",
                            FirstName = "System",
                            IsActive = true,
                            LastName = "Administrator",
                            PasswordHash = "AQAAAAEAACcQAAAAEIM9Gb9aogKUXsuO5FOBcvftv4BETrT9VGpGfYB7ER2nxW8eV2+oCBpkAZt8oxnXNw==",
                            PhoneNumber = "",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.ProductSide.Cart", b =>
                {
                    b.HasOne("ECommerceNew.Domain.Entities.UserSide.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("ECommerceNew.Domain.Entities.ProductSide.Cart", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.ProductSide.CartItem", b =>
                {
                    b.HasOne("ECommerceNew.Domain.Entities.ProductSide.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ECommerceNew.Domain.Entities.ProductSide.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.ProductSide.Product", b =>
                {
                    b.HasOne("ECommerceNew.Domain.Entities.ProductSide.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ECommerceNew.Domain.Entities.UserSide.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.ProductSide.ProductImage", b =>
                {
                    b.HasOne("ECommerceNew.Domain.Entities.ProductSide.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.ProductSide.Review", b =>
                {
                    b.HasOne("ECommerceNew.Domain.Entities.ProductSide.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ECommerceNew.Domain.Entities.UserSide.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.UserSide.User", b =>
                {
                    b.HasOne("ECommerceNew.Domain.Entities.UserSide.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.ProductSide.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.ProductSide.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("ProductImages");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.ProductSide.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.UserSide.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ECommerceNew.Domain.Entities.UserSide.User", b =>
                {
                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("Products");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
